### ISSUE TITLE
v2 change two state 

### ISSUE THREAD

**Issue by devmsh** [spatie/laravel-model-states#144] opened 2020-12-04 15:19 UTC
After upgrade to v2, when I try to transition twice in the same request it give me

```php
Error : Typed property Spatie\ModelStates\State::$field must not be accessed before initialization
 /Users/devmsh/projects/backend/vendor/spatie/laravel-model-states/src/State.php:233
 /Users/devmsh/projects/backend/vendor/spatie/laravel-model-states/src/State.php:140
```

**Comment by lorenzolosa** [comment] 2020-12-04 21:05
I got the same error. The problem is that transition() do not set the $field property when creating a new state. I've written a pull request for this in #145.

**Comment by brendt** [comment] 2020-12-09 06:19
Fixed in 2.0.1.

**Closed by brendt** 2020-12-09 06:19 UTC
